name = "NSDEBase"
uuid = "5aa61ba9-7752-4810-b2ec-484f26c3f007"
authors = ["Giancarlo A. Antonucci"]
version = "0.1.0"

[deps]
ArrowMacros = "46a4b217-d1c8-4502-9c1a-7bf73a71908c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
